# Action à définir dans le repository de FrameWork4 et 8

name: Set app version Action

env:
  repo_owner: fpinon14 
  repo_name: Framework4  
          
permissions:
  contents: write
  
# Controls when the workflow will run
on:
   # Allows you to run this workflow manually from the Actions tab
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  set_version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source 
        uses: actions/checkout@v4
     

   # Runs a single command using the runners shell
      - name: Set version in remote repo
        run: |
         event_type="trigger-workflow" 
          token="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"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $token" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$env.repo_owner/$env.repo_name/actions/workflows/increment_version.yml/dispatches \
            -d "{\"ref\": \"main\"}"
            
      - name: Checkout source 
        uses: actions/checkout@v4
     
      - name: Get revision file
        uses: actions/checkout@v4
        with:
          repository: fpinon14/Framework4          
          path: REVISIONS
          ref: main
    
      - name: Get version and add notes
        run: |
          #!/bin/sh
          
          git config --global user.email "pinon.fabien@gmail.com"
          git config --global user.name "fpinon14"

          GIT_VERSION=$(awk -F "=" '/GIT_VERSION/ {print $2}' current_rev.info)
          cat REVISIONS/current_rev.info
          echo $GIT_VERSION
          git notes add -f -m "Révision : "$GIT_VERSION

      - name: Push
        run: |
          git pull --rebase origin main
          git push --force origin  'refs/notes/*'
