# Action à définir dans les repositories des applis

name: Set app version Action

env:
  # Modifier ici le nom du Framework rattaché (Framework4 ou Framework8)
  framework_repo_name: Framework4
  # et le nom du token
  framework_token :  ${{ secrets.TOK_Framework4 }}
          
permissions:
  contents: write
  
on:
  push:

jobs:
  set_version:
    runs-on: ubuntu-latest

    steps:
      - name: Echos
        run: |
          echo Message : ${{ github.event.head_commit.message }}
          echo Repo actuel : ${{ github.repository }}
          
      - name: Set version in remote repo
        run: |
          token=${{ secrets.TOK_Framework4 }}
          commit_message=${{ github.event.head_commit.message }}
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $token" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{github.api_url}}/repos/${{github.repository_owner}}/${{env.framework_repo_name}}/actions/workflows/increment_version.yml/dispatches \
            -d '{"ref":"main","inputs":{"commit_message":\"$commit_message\","repo_source":"${{github.repository}}"}}' 
            
    
      - name: Get revision file
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository_owner }}/${{ env.framework_repo_name }}
          path: REVISIONS
          ref: main
          token: ${{ env.framework_token }}
    
      - name: Get version 
        run: |
          #!/bin/sh
          
          git config --global user.email "$GITHUB_ACTOR@$ADDRESS_SUFFIX" 
          git config --global user.name "$GITHUB_ACTOR"

          GIT_VERSION=$(awk -F "=" '/GIT_VERSION/ {print $2}' REVISIONS/REVISIONS/current_rev.info)
        
          echo Version récupérée : $GIT_VERSION
       
          echo "GIT_VERSION=$GIT_VERSION" >>$GITHUB_ENV
          
      - name: Checkout source 
        uses: actions/checkout@v4
     
      - name: Add Rev note and Push
        run: |
          #!/bin/sh
          echo Ajout de la note : Révision $GIT_VERSION
          git notes add -f -m "Révision : "$GIT_VERSION
          git push --force -u origin  'refs/notes/*'
