# Action à définir dans le repository de FrameWork4 et 8

name: Set app version Action

env:
  repo_name: Framework4  
          
permissions:
  contents: write
  
on:
  push:

jobs:
  set_version:
    env: 
      GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER
    runs-on: ubuntu-latest

    steps:
    
      - name: Set version in remote repo
        run: |
          token=${{ secrets.TOK_Framework4 }}
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $token" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $GITHUB_API_URL/repos/$GITHUB_REPOSITORY_OWNER/Framework4/actions/workflows/increment_version.yml/dispatches \
            -d '{"ref":"main"}' 
            
    
      - name: Get revision file
        uses: actions/checkout@v5
        with:
          repository: ${{ env.GITHUB_REPOSITORY_OWNER }}/Framework4  
          path: REVISIONS
          ref: main
          token: ${{ secrets.TOK_Framework4 }}
    
      - name: Get version 
        run: |
          #!/bin/sh
          
          git config --global user.email "pinon.fabien@gmail.com" 
          git config --global user.name "$GITHUB_ACTOR"

          GIT_VERSION=$(awk -F "=" '/GIT_VERSION/ {print $2}' REVISIONS/REVISIONS/current_rev.info)
        
          echo Version récupérée : $GIT_VERSION
       
          echo "GIT_VERSION=$GIT_VERSION" >>$GITHUB_ENV
          
      - name: Checkout source 
        uses: actions/checkout@v4
     
      - name: Add Rev note and Push
        run: |
          #!/bin/sh
          echo Ajout de la note : Révision $GIT_VERSION
          git notes add -f -m "Révision : "$GIT_VERSION
          git push --force -u origin  'refs/notes/*'
